### PR TITLE
docs: use installation script to deploy OpenFunction and deprecate the installation guide

### PR DESCRIPTION
**Pull request by lizzzcai**
update knative, tekton and keda versions to align with `hack/deploy.sh`, and add verification steps.

### CODE REVIEW

**Comment by tpiperatgod** [comment]
Thanks for the PR, but we plan to use only the installation script to deploy OpenFunction and its dependencies in the future, and to deprecate these files.

**Comment by tpiperatgod** [comment]
Maybe you can remove them in this PR. :smile:

**Comment by lizzzcai** [comment]
Hi @tpiperatgod. sure, I am glad to help to delete the docs in [Installation Guide](https://github.com/OpenFunction/OpenFunction/tree/main/docs/installation).

**Comment by lizzzcai** [comment]
Hi @tpiperatgod, I have made the changes to delete the [installation guide](https://github.com/OpenFunction/OpenFunction/tree/main/docs/installation) and update the README.md. Please review it.

Also I have a few suggestions,
For the [deploy.sh](https://github.com/OpenFunction/OpenFunction/blob/main/hack/deploy.sh), I suggest having a fixed version for Tekton rather than the `latest`, same for the Shipwright.
For the [delete.sh](https://github.com/OpenFunction/OpenFunction/blob/main/hack/delete.sh), I suggest deleting by `kubectl delete -f <component yaml>` to align with the deploy.sh, as it will be hard to maintain the list when the dependencies' version upgrade.

**Review by tpiperatgod — APPROVED** [review]

**Comment by tpiperatgod** [comment]
> Hi @tpiperatgod, I have made the changes to delete the [installation guide](https://github.com/OpenFunction/OpenFunction/tree/main/docs/installation) and update the README.md. Please review it.

Approved it. Thx!

> Also I have a few suggestions,
> For the [deploy.sh](https://github.com/OpenFunction/OpenFunction/blob/main/hack/deploy.sh), I suggest having a fixed version for Tekton rather than the `latest`, same for the Shipwright.
> For the [delete.sh](https://github.com/OpenFunction/OpenFunction/blob/main/hack/delete.sh), I suggest deleting by `kubectl delete -f <component yaml>` to align with the deploy.sh, as it will be hard to maintain the list when the dependencies' version upgrade.

It looks reasonable. What do you think, @wanjunlei?

**Pull request merged**
