### PR TITLE
Inherit labels from build

### PR DESCRIPTION
**Pull request by oops-oom**

### CODE REVIEW

**Comment by benjaminhuo** [comment]
@oops-oom Thanks for the contribution
You need to sign your commit:
```
git commit -s --amend
git push
```

**Comment by benjaminhuo** [comment]
@oops-oom You'll need to rebase the main branch:
```
git remote add upstream https://github.com/OpenFunction/OpenFunction.git
git fetch --all
git rebase upstream/main
git push -f
```

**Comment by benjaminhuo** [comment]
@wanjunlei pls help to review this

**Comment by benjaminhuo** [comment]
@wrongerror would you take a look at why the e2e timeout？

**Comment by wrongerror** [comment]
reason: 
```Unsupported Kafka.spec.kafka.version: 3.1.0. Supported versions are: [3.2.0, 3.2.1, 3.2.3, 3.3.1]```

how to fix: 
bump kafka.version to 3.2.0+
```
https://github.com/OpenFunction/OpenFunction/blob/main/config/samples/function-kafka-quick.yaml#L8
```
@oops-oom would you fix this in this pr？

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
