### PR TITLE
Remove the "genclient:noStatus" comments as the CRDs contain the .status field and need to update the .status

### PR DESCRIPTION
**Pull request by tpiperatgod**
Signed-off-by: laminar <fangtian@kubesphere.io>

### CODE REVIEW

**Comment by tpiperatgod** [comment]
I kept the `genclient:noStatus` of the Domain resource because it doesn't actually use the `.status` field, is this ok?

**Comment by benjaminhuo** [comment]
The core client is still v1alpha1 and v1alpha2, and the events API could be kept as v1alpha1?

**Comment by benjaminhuo** [comment]
Whenever there are code changes, `make verify` and then `make manifests` should be called which calls `generate fmt vet manifests` in order. `fmt` is necessary to format code in a standard way

**Comment by benjaminhuo** [comment]
> I kept the `genclient:noStatus` of the Domain resource because it doesn't actually use the `.status` field, is this ok?

There is no side effect removing it

**Comment by benjaminhuo** [comment]
`hack/update-codegen.sh` should be called after changing the client generating code, you can take a closer look at this pr https://github.com/OpenFunction/OpenFunction/pull/176

**Comment by benjaminhuo** [comment]
`test: manifests generate fmt vet` should be changed to `test: generate fmt vet manifests`

**Comment by benjaminhuo** [comment]
There is `apis/core/v1alpha2/doc.go` but no `apis/core/v1beta1/doc.go`

`apis/core/v1alpha1/groupversion_info.go` is updated in https://github.com/OpenFunction/OpenFunction/pull/176/files#diff-ac43e92b1134b1a849fdce2761bc9861f3d28d74b534b52ba31deda91bb57866R28

similar change should be made to v1beta1?

**Comment by tpiperatgod** [comment]
Add the `doc.go`.

**Review by benjaminhuo — APPROVED** [review]

**Pull request merged**
