### PR TITLE
feat: Upgrade KEDA to v2.10.1 and HPA(autoscaling) api version to v2

### PR DESCRIPTION
**Pull request by tpiperatgod**
- upgrade deps version (keda to v2.10.1, client-go to 0.26.2, controller-runtime to v0.14.5)
- upgrade hpa api version to v2
- fix ut
- improve makefile (add `--server-side=true` to `kubectl apply` command and so on)
- adjust `scaledobject.fallback` field
- update ci

### CODE REVIEW

**Comment by benjaminhuo** [comment]
Great, thanks @tpiperatgod 
Looks like the e2e test is failing

**Comment by tpiperatgod** [comment]
I'll run the e2e test on my local machine and post the results

**Comment by benjaminhuo** [comment]
image
The error is because of resource limit of github action?

**Comment by tpiperatgod** [comment]
Kind needs to be upgraded to v0.20.0 to fix this issue, and the cluster is now running. If there are exceptions in subsequent cases, it means we need to update the test cases with the works mentioned in issue #475

**Comment by benjaminhuo** [comment]
Looks like the timeout is too small:
image

https://github.com/OpenFunction/OpenFunction/blob/main/.github/workflows/main.yaml#L170

**Comment by benjaminhuo** [comment]
Merge this for now,  you'll fix the below error in PR https://github.com/OpenFunction/OpenFunction/issues/475 ? @tpiperatgod 
https://github.com/OpenFunction/OpenFunction/actions/runs/5807297811/job/15749808744?pr=476

**Comment by tpiperatgod** [comment]
> Merge this for now, you'll fix the below error in PR #475 ? @tpiperatgod https://github.com/OpenFunction/OpenFunction/actions/runs/5807297811/job/15749808744?pr=476

ok, I think it'll work.

**Pull request merged**
