### PR TITLE
Support to keep the completed builders

### PR DESCRIPTION
**Pull request by wanjunlei**
Signed-off-by: wanjunlei <wanjunlei@yunify.com>

Support to keep the builder after the build is completed, associated issue #168.

You can customize the number of successful builders and failed builders that need to be retained by editing the `Function` like this:

```
spec:
  build:
    successfulBuildersHistoryLimit: 2
    failedBuildersHistoryLimit: 3
```

By default, the `successfulBuildersHistoryLimit` is 0, and `failedBuildersHistoryLimit` is 1.

You can also set the expiration time of the completed builder by editing the `Function` like this:

```
spec:
  build:
    builderMaxAge: 1d
```

By default, the `builderMaxAge` is 0, meaning never delete the builder.

This pr also modified the CI mechanism, and now uses ginkgo for e2e testing.

### CODE REVIEW

**Comment by benjaminhuo** [comment]
This is a big enhancement. A few comments:
- successfulBuildersHistoryLimit could be changed to successfulBuildsHistoryLimit
- failedBuildersHistoryLimit could be changed to failedBuildsHistoryLimit

The default value 0 of builderMaxAge is not good, set it to 1d is ok

@wanjunlei

**Comment by wanjunlei** [comment]
> 

By default, the successful builder will not be retained, only one failed builder will be retained, it will not cause unlimited growth of data, so 0 is also reasonable. The default value of non-zero will cause a problem. Builders that fail to execute will be automatically deleted, which is not conducive to debugging.

**Comment by wanjunlei** [comment]
CI needs to be changed, I turn off this pr, and reopen it after modifying ci.

**Comment by benjaminhuo** [comment]
> * successfulBuildersHistoryLimit could be changed to successfulBuildsHistoryLimit
> * failedBuildersHistoryLimit could be changed to failedBuildsHistoryLimit

OK, and the name could be simplified to `successfulBuildHistoryLimit` and `failedBuildHistoryLimit`.
It's more natural than Builds and Builders doesn't

**Pull request closed without merging**
